---
services:
  nginx:
    image: honeok/nginx:alpine
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/conf.d:/etc/nginx/conf.d
      - $PWD/certs:/etc/nginx/certs
      - $PWD/html:/usr/share/nginx/html
      - $PWD/logs:/var/log/nginx
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=256m
    network_mode: host
    # cap_add:
    #   - SYS_ADMIN
