# https://www.nodeseek.com/post-551782-1#9

[log]
level = "off"
output = "/dev/null"

[network]
no_tcp = false
use_udp = true

[[endpoints]]
listen = "0.0.0.0:10000"
remote = "1.1.1.1:443"

[[endpoints]]
listen = "0.0.0.0:20000"
remote = "8.8.8.8:443"
