services:
  openresty:
    image: honeok/openresty:alpine
    container_name: openresty
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - $PWD/conf.d:/etc/nginx/conf.d
      - $PWD/certs:/etc/nginx/certs
      - $PWD/html:/usr/local/openresty/nginx/html
      - $PWD/logs:/usr/local/openresty/nginx/logs
    tmpfs:
      - /var/cache/openresty:rw,noexec,nosuid,size=256m
    network_mode: host
    cap_add:
      - SYS_ADMIN
