---
name: "Build v1"

on:
  push:
    branches:
      - master
    paths:
      - "v1/**"
      - "!v1/**.md"
  # schedule:
  #   - cron: "0 16 * * *"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
  REGISTRY_IMAGE: ${{ secrets.DOCKER_USERNAME }}/nezha-dashboard

jobs:
  check:
    name: "Build pre check"
    runs-on: ubuntu-latest

    steps:
      - name: "Fetch Versions and Determine Build"
        id: bump_version
        run: |
          LATEST_VER="$(wget -qO- --tries=50 --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/nezhahq/nezha/releases/latest | grep '"tag_name":' | sed -n 's/.*"tag_name": "\(v[0-9.]*\)".*/\1/p')"
          CURRENT_VER="$(wget -qO- --tries=50 https://hub.docker.com/v2/repositories/honeok/nezha-dashboard/tags 2>/dev/null | grep -o '"name":"[^"]*"' | awk -F'"' '$4!="latest"{print $4}' | sort -rV | head -n1 || true)"
          CURRENT_DAY="$(date -u '+%d' -d '+8 hours')"
          echo "nezha_version=${LATEST_VER}" >> "$GITHUB_OUTPUT"
          if [[ "$(printf '%s\n%s\n' "$LATEST_VER" "$CURRENT_VER" | sort -V | head -n1)" != "$LATEST_VER" || -z "$CURRENT_VER" && -n "$LATEST_VER" || "$CURRENT_DAY" == "01" ]]; then
            echo "build_image=1" >> "$GITHUB_OUTPUT"
          fi

  build:
    needs:
      - check
    strategy:
      fail-fast: true
      matrix:
        include:
          - { platform: linux/amd64, os: ubuntu-latest }
          - { platform: linux/arm64, os: ubuntu-24.04-arm }
          - { platform: linux/s390x, os: ubuntu-latest }
    runs-on: ${{ matrix.os }}
    name: "Build ${{ matrix.platform }} for DockerHub"

    steps:
      - name: "Prepare"
        run: |
          PLATFORM=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${PLATFORM//\//-}" >> "$GITHUB_ENV"

      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Extract Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
