---
name: "Build v0"

on:
  push:
    branches:
      - master
    paths:
      - "v0/**"
      - "!v0/**.md"
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}

jobs:
  check:
    name: "Pre check"
    runs-on: ubuntu-latest
    outputs:
      trigger: ${{ steps.bump_version.outputs.trigger }}

    steps:
      - name: "Fetch Versions and Decide"
        id: bump_version
        run: |
          set -eEuxo pipefail
          TRIGGER="false"
          CURRENT_DAY="$(date -u '+%d' -d '+8 hours')"
          if [[ "$CURRENT_DAY" == "01" ]] || [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Build required."
            TRIGGER="true"
          else
            echo "No build required."
          fi
          echo "trigger=${TRIGGER}" >> "$GITHUB_OUTPUT"

  release:
    needs:
      - check
    if: needs.check.outputs.trigger == 'true'
    strategy:
      fail-fast: true
      matrix:
        nezha_version:
          - v0.18.6
          - v0.20.13
    runs-on: ubuntu-latest
    name: "Build binary"

    steps:
      - name: "checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Remove existing tag"
        run: |
          if git tag --list | grep -q "^${{ matrix.nezha_version }}$"; then
            git push origin --delete ${{ matrix.nezha_version }}
          fi

      - name: "Clone source code"
        working-directory: v0
        run: |
          set -eEuxo pipefail
          mkdir src
          git clone --depth=1 --branch ${{ matrix.nezha_version }} https://github.com/nezhahq/nezha.git src

      - name: "Prepare assets"
        working-directory: v0/src
        run: |
          set -eEuxo pipefail
          cp ../build.sh .
          chmod +x build.sh
          ./build.sh
          rm -f pkg/geoip/geoip.db
          wget --tries=5 --no-check-certificate -qO pkg/geoip/geoip.db https://ipinfo.io/data/free/country.mmdb?token=${IPINFO_TOKEN}

      - name: "Extract version"
        id: bump_version
        run: |
          set -eEuxo pipefail
          go_version="$(wget --tries=5 --no-check-certificate -qO- https://go.dev/dl/?mode=json | awk '/version/ {print $2}' | sed -n '1s/.*"go\([0-9]*\.[0-9]*\).*/\1/p')"
          echo "nezha_version=$(sed 's/^v//' <<< ${{ matrix.nezha_version }})" >> "$GITHUB_OUTPUT"
          echo "go_version=$go_version" >> "$GITHUB_OUTPUT"

      - name: "Build binaries"
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: ${{ steps.bump_version.outputs.go_version }}
          dest: dist
          pkg: cmd/dashboard
          prefix: dashboard
          targets: linux/amd64,linux/arm64,linux/s390x
          v: true
          x: false
          race: false
          tags: timetzdata
          ldflags: -s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=${{ steps.bump_version.outputs.nezha_version }}
          buildmode: default
          trimpath: true
          working_dir: ${{ github.workspace }}/v0/src

      - name: "Package assets"
        working-directory: ${{ github.workspace }}/v0/src
        run: |
          set -eEuxo pipefail
          cd dist
          for FILE in *; do
            if [ -f "$FILE" ]; then
              PLATFORM=${FILE#dashboard-}
              PACKAGE_NAME="dashboard-${{ steps.bump_version.outputs.nezha_version }}-${PLATFORM}"
              mkdir "$PACKAGE_NAME"
              cp "$FILE" "${PACKAGE_NAME}/dashboard"
              sha256sum "${PACKAGE_NAME}/dashboard" | sed 's| .*| dashboard|' > ./${PACKAGE_NAME}/checksum.txt"
              cp $GITHUB_WORKSPACE/LICENSE ./${PACKAGE_NAME}
              cp $GITHUB_WORKSPACE/README.md ./${PACKAGE_NAME}
              tar cfz "${PACKAGE_NAME}.tar.gz" ./${PACKAGE_NAME}
              rm -rf ./${PACKAGE_NAME}
            fi
          done
          cd ..

      - name: "Upload Release"
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: Automated build release.
          files: ${{ github.workspace }}/v0/src/dist/*.tar.gz
          overwrite_files: true
          name: ${{ matrix.nezha_version }}
          tag_name: ${{ matrix.nezha_version }}
          fail_on_unmatched_files: true
