---
name: "Build v1"

on:
  # schedule:
  #   - cron: "0 16 * * *"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
  REGISTRY_IMAGE: ${{ secrets.DOCKER_USERNAME }}/nezha-dashboard

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - { platform: linux/amd64, os: ubuntu-latest }
          - { platform: linux/arm64, os: ubuntu-24.04-arm }
          - { platform: linux/s390x, os: ubuntu-latest }
    runs-on: ${{ matrix.os }}
    name: "Build ${{ matrix.platform }} for DockerHub"

    steps:
      - name: "Prepare"
        run: |
          PLATFORM=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${PLATFORM//\//-}" >> "$GITHUB_ENV"

      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Extract Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
