---
name: "centos"

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/centos.yaml"
      - "infra/centos.sh"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os:
          - almalinux:8
          - almalinux:9
          - almalinux:10
          # - quay.io/centos/centos:centos7.9.2009
          - quay.io/centos/centos:9
          - quay.io/centos/centos:10
          - rockylinux/rockylinux:8
          - rockylinux/rockylinux:9
          - rockylinux/rockylinux:10
          # - registry.redhat.io/quay/quay-rhel8
          # - registry.redhat.io/quay/quay-rhel9
    container:
      image: ${{ matrix.os }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Prepare and run kernel.sh"
        working-directory: ${{ github.workspace }}/infra
        run: |
          bash kernel-deps.sh
          GITHUB_CI=1
          bash -x centos.sh
