---
name: "Dependabot Auto merge"

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: "Dependabot Auto merge"
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch'

    steps:
      - name: "Auto merge for Dependabot PR"
        env:
          GH_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_LIST="$(gh pr list --state open --app dependabot --json url --jq '.[].url')"
          [ -z "$PR_LIST" ] && exit 0

          for PR_URL in $PR_LIST; do
            gh pr merge --auto --merge "$PR_URL"
          done
