---
name: "Dependabot Auto merge"

on:
  pull_request:
  workflow_dispatch:

jobs:
  dependabot:
    name: "Dependabot Auto merge"
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}

    steps:
      - name: "Auto merge for Dependabot PR"
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
