---
name: "kernel.sh"

on:
  push:
    branches:
      - master
    paths:
      - "infra/kernel.*"
  workflow_dispatch:

jobs:
  run:
    name: "Test kernel.sh on multiple os"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - bullseye
          - bookworm
          - trixie

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run kernel.sh"
        working-directory: ${{ github.workspace }}/infra
        run: sudo bash kernel.sh --debug --ci
