---
name: "Test kernel.sh multi OS compatibility"

on:
  push:
    branches:
      - master
    paths:
      - "infra/kernel.*"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu:jammy
          - ubuntu:noble
          - ubuntu:plucky
          - ubuntu:rolling
          - debian:bullseye
          - debian:bookworm
          - debian:trixie
          - debian:sid
    container:
      image: ${{ matrix.os }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Install Dependencies"
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y bash curl

      - name: "Run kernel.sh"
        working-directory: ${{ github.workspace }}/infra
        run: bash kernel.sh --debug --ci
