---
name: "kernel script CI"

on:
  push:
    branches:
      - master
    paths:
      - "infra/kernel*.*"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu:jammy # 22.04
          - ubuntu:noble # 24.04
          - ubuntu:plucky # 25.04
          - ubuntu:rolling
          - debian:bookworm # 12
          - debian:trixie # 13
          - debian:sid
    container:
      image: ${{ matrix.os }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Prepare and run kernel.sh"
        working-directory: ${{ github.workspace }}/infra
        run: |
          bash kernel-ci-extensions.sh
          bash kernel.sh --debug --ci
