---
name: "kernel.sh"

on:
  push:
    branches:
      - master
    paths:
      - "infra/kernel.*"
  workflow_dispatch:

jobs:
  run:
    name: "Main program running"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Main program running"
        working-directory: ${{ github.workspace }}/infra
        run: |
          sudo bash kernel.sh --debug ci
