---
name: "Pin Digests"

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/pin-digests.yaml"
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  digests:
    name: "Pin Digests"
    runs-on: ubuntu-latest

    steps:
      - name: "Generate App Token"
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 #v1.12.0
        id: app-token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: "Checkout repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          ref: master
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: "Install extension"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          set -eEuxo pipefail
          gh extension install amenocal/gh-pin-actions

      - name: "Pin Actions Digests"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          set -eEuxo pipefail
          cd $GITHUB_WORKSPACE || exit 1
          gh pin-actions workflows --overwrite
          if ! git diff-index --quiet HEAD --; then
            echo "IS_RENEW=1" >> "$GITHUB_ENV"
          fi

      - name: "Upload commit to repository"
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 #v7.1.0
        if: ${{ env.IS_RENEW != '' }}
        with:
          commit_message: "chore: pin GitHub Actions to specific SHAs"
          branch: ${{ github.ref }}
          commit_options: "--signoff --no-verify"
          commit_user_name: honego[bot]
          commit_user_email: 2596419+honego[bot]@users.noreply.github.com
          commit_author: honego[bot] <2596419+honego[bot]@users.noreply.github.com>
