---
name: "Shellcheck"

on:
  push:
    branches:
      - "**"
    paths:
      - "**/*.sh"
      - ".github/workflows/shellcheck.yaml"
  pull_request:
    paths:
      - "**/*.sh"
      - ".github/workflows/shellcheck.yaml"
  workflow_dispatch:

jobs:
  shellcheck:
    name: "Run shellcheck"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: "Run shellcheck"
        uses: luizm/action-sh-checker@a3627bbade03e7684152ea3f66d1d350d6cfac14 # master
        env:
          SHFMT_OPTS: -i 4 -sr
